quarkus.datasource.db-kind=db2
quarkus.datasource.jdbc.url=${DB2_JDBC_URL}
quarkus.datasource.username=${DB2_USERNAME}
quarkus.datasource.password=${DB2_PASSWORD}
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
quarkus.rest-csrf.require-form-url-encoded=false

%dev.quarkus.datasource.jdbc.url=jdbc:db2://localhost:50000/todoapp
%dev.quarkus.datasource.username=db2inst1
%dev.quarkus.datasource.password=passw0rd

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:tasks;MODE=DB2;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.hibernate-orm.database.generation=none
%test.quarkus.flyway.migrate-at-start=true

%dev.quarkus.hibernate-orm.log.sql=true
