CREATE TABLE tasks (
    id CHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description CLOB,
    status VARCHAR(16) NOT NULL,
    due_date TIMESTAMP,
    priority SMALLINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT ck_tasks_status CHECK (status IN ('open', 'completed'))
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uq_tags_name UNIQUE (name)
);

CREATE TABLE task_tags (
    task_id CHAR(36) NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_task_tags PRIMARY KEY (task_id, tag_id),
    CONSTRAINT fk_task_tags_task FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE task_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id CHAR(36) NOT NULL,
    action VARCHAR(32) NOT NULL,
    before_snapshot CLOB,
    after_snapshot CLOB,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_task_audit PRIMARY KEY (id),
    CONSTRAINT ck_task_audit_action CHECK (action IN ('create', 'update', 'delete', 'restore', 'hard_delete'))
);
